### ISSUE TITLE
falcon-sensor-6.49.0-14606.el7.s390x failing to meet dependencies 

### ISSUE THREAD

**Issue by gurlal-cr** [CrowdStrike/chef-falcon#40]
Hi Team,
We are having issue with installing crowstrike via chef recipe on rhel 7 where it is failing to meet dependencies, error is below.
```
STDERR: warning: /opt/CrowdStrike/sensor_installer: Header V4 RSA/SHA512 Signature, key ID xxxxxx: NOKEY
error: Failed dependencies:
    libc.so.6(GLIBC_2.2)(64bit) is needed by falcon-sensor-6.49.0-14606.el7.s390x
    libc.so.6(GLIBC_2.2.3)(64bit) is needed by falcon-sensor-6.49.0-14606.el7.s390x
    libdl.so.2(GLIBC_2.2)(64bit) is needed by falcon-sensor-6.49.0-14606.el7.s390x
    libm.so.6(GLIBC_2.2)(64bit) is needed by falcon-sensor-6.49.0-14606.el7.s390x
    libpthread.so.0(GLIBC_2.2)(64bit) is needed by falcon-sensor-6.49.0-14606.el7.s390x
    librt.so.1(GLIBC_2.2)(64bit) is needed by falcon-sensor-6.49.0-14606.el7.s390x
---- End output of ["rpm", "-U", "--oldpackage", "/opt/CrowdStrike/sensor_installer"] ----
```
Looks issue was encountered for ansible as [well](https://github.com/CrowdStrike/ansible_collection_falcon/issues/278) and that has been fixed.

Thanks,

**Comment by carlosmmatos** [comment]
I'll try to get this uploaded asap

**Comment by carlosmmatos** [comment]
Fixed by #41

**Comment by carlosmmatos** [comment]
@gurlal-cr New version has been uploaded to the supermarket. Please double check, and if all is good, close this issue.

Thanks!

**Comment by gurlal-cr** [comment]
Thanks, will test it shortly

**Comment by gurlal-cr** [comment]
It appears that the issue has not been resolved yet. I will consult with our internal team about the status of the falcon cookbook and try again tomorrow

**Comment by gurlal-cr** [comment]
hi @carlosmmatos we have tried again and it is still not working on rhel 7. We have a custom cookbook that is similar to one on supermarket that uses API method to download sensor (bas url - https://api.eu-1.crowdstrike.com/....)
If you think this isn't a code issue anymore. i am happy to close the issue and open a ticket with support, let me know

**Comment by carlosmmatos** [comment]
@gurlal-cr Can you please provide us with an output of your hosts' attributes (via `ohai`)?

**Comment by gurlal-cr** [comment]
@carlosmmatos certainly. anything in particular from ohai output?

**Comment by ffalor** [comment]
Hey @gurlal-cr we use `node['kernel']['machine']` to build the query that is used to download the correct sensor. We are trying to determine if a value is returning that we are not accounting for.

Also what type of query are you doing?
 - sensor_update_policy
 - version
 - version_decrement
 
 This will help us narrow down what parts of the filters are being hit.

**Comment by gurlal-cr** [comment]
hey @ffalor @carlosmmatos 
we made some modifications to our cookbook on how it is querying linux package and it working now. It was downloading the incompatible package 
node['kernel']['machine'] returns`[ "x86_64"]` which appears to accounted [for](https://github.com/CrowdStrike/chef-falcon/blob/main/libraries/helpers.rb#L11) and cookbook queries the falcon sensor version

**Comment by carlosmmatos** [comment]
@gurlal-cr I'm curious what modifications where needed on your side since version 0.1.2 should account for that kernel architecture and provide the proper API filter. Makes me wonder if somehow you're not pulling in the latest cookbook. Do you see this when running:
```
Synchronizing cookbooks:
 - falcon (0.1.2)
```
